### ISSUE TITLE
Most Optimized BFS Algorithm

### ISSUE THREAD

**Issue by panditakshay402** [panditakshay402/Hacktoberfest2023#1]
PR will be accepted if Explained properly!

**Comment by okaydivyansh** [comment]
assign this issue to me

**Comment by okaydivyansh** [comment]
#7 will close this issue

**Comment by kunjshukla** [comment]
Hey there, can you please assign me this issue.

**Comment by panditakshay402** [comment]
@kunjshukla i have assigned u must do FOLLOW AND STAR THE REPO

**Comment by Adi-456** [comment]
Kindly assign it to me.

**Comment by rahulmangla28** [comment]
Please assign this to me.
