### ISSUE TITLE
LinkedList

### ISSUE THREAD

**Issue by nehal-5** [panditakshay402/Hacktoberfest2023#159]
Hello @panditakshay402, I would like to code all operations of LinkedList

**Comment by atharvam2004** [comment]
I would like to solve this issue

**Comment by Ayush-Garg1** [comment]
Hello @panditakshay402 , I would like to perform all the operations related to LinkedList.
Please Assign.

**Comment by Suprabha24** [comment]
Can you please assign this issue to me .
