### ISSUE TITLE
PRINT NAME "N" TIMES WITHOUT LOOP

### ISSUE THREAD

**Issue by panditakshay402** [panditakshay402/Hacktoberfest2023#2]
use recursion.

**Comment by okaydivyansh** [comment]
Can you please assign this issue to me?

**Comment by RashiJyotishi** [comment]
@panditakshay402 please assign this issue to me.

**Comment by panditakshay402** [comment]
@RashiJyotishi  must follow me and star the repo before PR

**Comment by devvkumar** [comment]
please assign this task to me.

**Comment by aryan-rohit** [comment]
@panditakshay402 please assign this to me

**Comment by AckermanLevi1** [comment]
@panditakshay402 I would love to contribute in it

**Comment by panditakshay402** [comment]
@okaydivyansh @devvkumar @aryan-rohit @AckermanLevi1  Assigned Do Follow me and Star the REPO before PR !!!

**Comment by AckermanLevi1** [comment]
Done [N times name file added](https://github.com/panditakshay402/Hacktoberfest2023/pull/49) #49

**Comment by panditakshay402** [comment]
> Done [N times name file added](https://github.com/panditakshay402/Hacktoberfest2023/pull/49) #49 pls merge it

ok

**Comment by devvkumar** [comment]
Done #49 Please Merge it

**Comment by vivek5200** [comment]
Hey @panditakshay402 Please Assign me to this problem .

**Comment by RashiJyotishi** [comment]
I created a pull request for this issue, and you merged it. However, on the official Hacktoberfest website, it is showing that it is excluded.
