### ISSUE TITLE
Symmetric Tree

### ISSUE THREAD

**Issue by gh4abhi** [panditakshay402/Hacktoberfest2023#214]
Problem Link - https://leetcode.com/problems/symmetric-tree/description/

Given the root of a binary tree, check whether it is a mirror of itself (i.e., symmetric around its center).

 

Example 1:

Input: root = [1,2,2,3,4,4,3]
Output: true
Example 2:

Input: root = [1,2,2,null,3,null,3]
Output: false
 

Constraints:

The number of nodes in the tree is in the range [1, 1000].
-100 <= Node.val <= 100

**Comment by gh4abhi** [comment]
Please assign this issue to me.

**Comment by ArshiyaArora** [comment]
Please assign me this. I want to contribute in hacktoberfest

**Comment by divya1515** [comment]
Please assign me this issue

**Comment by ArshiyaArora** [comment]
I have sent you PR please add it
