### ISSUE TITLE
feat: Add Wave Print Matrix Program 

### ISSUE THREAD

**Issue by khushis28** [panditakshay402/Hacktoberfest2023#222]
A "wave print matrix program" could be a program that prints a matrix (a two-dimensional array) in a "wave-like" pattern. In other words, it might print the elements of the matrix in a way that resembles the motion of a wave. 

For example, if you have a 2D matrix like this:

1  2  3
4  5  6
7  8  9

A "wave print" of this matrix could look like:

1  4  7  8  5  2  3  6  9

**Comment by mreshank** [comment]
I can do it easily ! assign it to me please ...

**Comment by mreshank** [comment]
@panditakshay402 , please merge my PR, i've already added a PR with the code. I dont have write access in this repo. I believe.
