### ISSUE TITLE
Add Dijkstra's Algorithm 

### ISSUE THREAD

**Issue by shubhdevv** [panditakshay402/Hacktoberfest2023#247]

**Comment by shubhdevv** [comment]
hey @panditakshay402 , please assign me this issue

**Comment by ankitasray** [comment]
Can you assign me this issue ,please! @panditakshay402

**Comment by shubhdevv** [comment]
hey @panditakshay402 , please check the pull request and add the hacktoberfest-accepted label if possible

**Comment by ankitasray** [comment]
I solved, please check the pull request. @panditakshay402
