### ISSUE TITLE
Prim's and Kruskal's Algo in C++

### ISSUE THREAD

**Issue by panditakshay402** [panditakshay402/Hacktoberfest2023#3]
send PR with explanation

**Comment by tvermaashutosh** [comment]
\assign @panditakshay402

**Comment by ShivanshDengla** [comment]
can you assign this to me

**Comment by panditakshay402** [comment]
@ShivanshDengla HEY i have assigned you , Must do FOLLOW me and STAR the repo before PR!

**Comment by ShivanshDengla** [comment]
Followed and starred, pull request for prims - https://github.com/panditakshay402/Hacktoberfest2023/pull/19

**Comment by ShivanshDengla** [comment]
Added Krusalk's algorithm as well - https://github.com/panditakshay402/Hacktoberfest2023/pull/27

**Comment by panditakshay402** [comment]
> Added Krusalk's algorithm as well - #
Ok

**Comment by rahulmangla28** [comment]
Please assign this to me.

**Comment by aryan-rohit** [comment]
@panditakshay402  assign this to me

**Comment by SonjeVilas** [comment]
Can you please assign me this problem

**Comment by AviGawande** [comment]
could you please assign me this repo to contribute
