### ISSUE TITLE
PROBLEMS ON ARRAYS

### ISSUE THREAD

**Issue by panditakshay402** [panditakshay402/Hacktoberfest2023#33]
MUST DO FOLLOW AND STAR THE REPO BEFORE PR !!! 

YOUR CODE MUST CONTAIN EXPLANATIONS
ANY LANGUAGE CAN BE USED !

**Comment by harshitadharamansharma** [comment]
Please assign this to me.

**Comment by rahulmangla28** [comment]
Please assign this to me.

**Comment by Adi-456** [comment]
I would like to contribute in this issue.

**Comment by MahraibFatima** [comment]
Please assign this to me.

**Comment by naruxor** [comment]
Please assign this to me.

**Comment by panditakshay402** [comment]
@Adi-456 @MahraibFatima @naruxor Do Follow me and Star the REPO before PR !!!

**Comment by kmanishprogrammar** [comment]
please assign this to me as i would like to work on it

**Comment by vivek5200** [comment]
Hey @panditakshay402  ,Please assign this task to me. I will surely follow and star your repo.

**Comment by spardha-codinggirl** [comment]
Hi @panditakshay402 , I want to work on this issue. Please assign this to me.

**Comment by Anjali-Git-Hub** [comment]
hi @panditakshay402 , please assign this issue to me .

**Comment by Kirti-Pant** [comment]
@panditakshay402  sir, please assign me this issue as my first open source contribution.

**Comment by Abhi9354** [comment]
please assign to me

**Comment by rakeem996** [comment]
@panditakshay402 sir, please assign me this issue as my first time contributing to open source .

**Comment by rakeem996** [comment]
@panditakshay402 I have created a pull request please look into it

**Comment by harshitadharamansharma** [comment]
@panditakshay402 I have created a PR. #225

**Comment by vamus092** [comment]
assign me the task

**Comment by Kirti-Pant** [comment]
is this repository excluded from hacktoberfest2023??
