### ISSUE TITLE
PROBLEMS ON GRAPH

### ISSUE THREAD

**Issue by panditakshay402** [panditakshay402/Hacktoberfest2023#34]
MUST DO FOLLOW AND STAR THE REPO BEFORE PR !!! 

YOUR CODE MUST CONTAIN EXPLANATIONS
ANY LANGUAGE CAN BE USED !

**Comment by Adi-456** [comment]
@panditakshay402 please assign it to me.

**Comment by rahulmangla28** [comment]
Please assign this to me.

**Comment by aryan-rohit** [comment]
@panditakshay402 assign this to me

**Comment by vivek5200** [comment]
@panditakshay402 Please Assign This To me Brother .

**Comment by wasiuddinmansoori1** [comment]
Assign to me please

**Comment by harshitadharamansharma** [comment]
@panditakshay402 I have created a PR. #225 and added a program in C++/Graph
