### ISSUE TITLE
PROBLEMS USING VECTORS

### ISSUE THREAD

**Issue by panditakshay402** [panditakshay402/Hacktoberfest2023#35]
MUST DO FOLLOW AND STAR THE REPO BEFORE PR !!! 

YOUR CODE MUST CONTAIN EXPLANATIONS
ANY LANGUAGE CAN BE USED !

**Comment by Adi-456** [comment]
@panditakshay402 Please assign this issue to me.

**Comment by naruxor** [comment]
As I am new to Git, I want to do a real life pull request and I have a pretty good understanding of vectors in C++. Please assign the issue to me and I hope I'll be able to make the necessary and desired changes.

**Comment by panditakshay402** [comment]
@naruxor Do Follow me and Star the REPO before PR !!!

**Comment by naruxor** [comment]
Sure, Thank You

**Comment by imdarshansingh** [comment]
Please assign this issue to me.

**Comment by Rex1713** [comment]
Please assign this issue to me
