### ISSUE TITLE
PROBLEMS USING PAIR

### ISSUE THREAD

**Issue by panditakshay402** [panditakshay402/Hacktoberfest2023#36]
MUST DO FOLLOW AND STAR THE REPO BEFORE PR !!! 

YOUR CODE MUST CONTAIN EXPLANATIONS
ANY LANGUAGE CAN BE USED !

**Comment by the-shivam-gupta** [comment]
can u plz elaborate the problem?

**Comment by panditakshay402** [comment]
> can u plz elaborate the problem?

IN C++ STL there is pair (google for more details)

**Comment by rahulmangla28** [comment]
Please assign this to me.

**Comment by Adi-456** [comment]
Kindly assign it to me.
