### ISSUE TITLE
PROBLEMS ON HEAP

### ISSUE THREAD

**Issue by panditakshay402** [panditakshay402/Hacktoberfest2023#37]
MUST DO FOLLOW AND STAR THE REPO BEFORE PR !!! 

YOUR CODE MUST CONTAIN EXPLANATIONS
ANY LANGUAGE CAN BE USED !

**Comment by aryan-rohit** [comment]
@panditakshay402  assign this issue to me

**Comment by rahulmangla28** [comment]
Please assign this to me.

**Comment by Adi-456** [comment]
Kindly assign this issue to me.

**Comment by ankitasray** [comment]
assign me for this issue ,please @panditakshay402
