### ISSUE TITLE
PROBLEMS ON STACKS

### ISSUE THREAD

**Issue by panditakshay402** [panditakshay402/Hacktoberfest2023#38]
MUST DO FOLLOW AND STAR THE REPO BEFORE PR !!! 

YOUR CODE MUST CONTAIN EXPLANATIONS
ANY LANGUAGE CAN BE USED !

**Comment by Adi-456** [comment]
@panditakshay402 kindly assign it to me.

**Comment by kmanishprogrammar** [comment]
please assign this to me as i would like to work on it

**Comment by SonjeVilas** [comment]
please assign me this problem

**Comment by panditakshay402** [comment]
@SonjeVilas DO FOLLOW ME AND STAR THE REPO BEFORE PR!!!

**Comment by AviGawande** [comment]
@panditakshay402  will be glad to contribute if you assigned me this Project to work.

**Comment by AdityaDhavale** [comment]
@panditakshay402 I would like to work on this issue , will u please assign me?

**Comment by ReaganBlade** [comment]
I would like to work on this problem, can you please assign this to me?
