### ISSUE TITLE
PROBLEMS ON DP

### ISSUE THREAD

**Issue by panditakshay402** [panditakshay402/Hacktoberfest2023#39]
MUST DO FOLLOW AND STAR THE REPO BEFORE PR !!! 

YOUR CODE MUST CONTAIN EXPLANATIONS
ANY LANGUAGE CAN BE USED !

**Comment by aryan-rohit** [comment]
@panditakshay402  please assign this issue to me

**Comment by rahulmangla28** [comment]
Please assign this to me.

**Comment by Adi-456** [comment]
Kindly assign it to me.

**Comment by haxshith** [comment]
I request you to kindly assign me this issue

**Comment by alaykabir** [comment]
Hey! Can you please assign this issue to me. I am willing to contribute.

**Comment by mdsahilnoob** [comment]
@panditakshay402 can you please assign this issue to me?
