### ISSUE TITLE
Pattern programs in C

### ISSUE THREAD

**Issue by panditakshay402** [panditakshay402/Hacktoberfest2023#4]
MUST Contain EXPLANATION!!!👉👉👉👉

**Comment by khushpreetsinghb** [comment]
I am new to open source, I want to work on this issue. Can you please assign this to me. And also explain that which pattern I have to print or make.

**Comment by tvermaashutosh** [comment]
@panditakshay402

**Comment by alienishi** [comment]
Please Assign me this issue 
I am new to open source 
@panditakshay402

**Comment by panditakshay402** [comment]
Do STAR the repo and  FORK and  send PR !! @tvermaashutosh @khushpreetsinghb @alienishi

**Comment by khushpreetsinghb** [comment]
Which pattern I have to print ?

**Comment by panditakshay402** [comment]
> Which pattern I have to print ?

@khushpreetsinghb ANY!

**Comment by panditakshay402** [comment]
@alienishi @khushpreetsinghb @tvermaashutosh  MUST DO FOLLOW , FORK the Repo, START

**Comment by alienishi** [comment]
Followed and Starred

**Comment by khushpreetsinghb** [comment]
I have also followed and starred.

**Comment by khushpreetsinghb** [comment]
Thank you

**Comment by panditakshay402** [comment]
> Thank you

welcome

**Comment by Kundanika04** [comment]
Hey, I am new to open source. Can I contribute to this?

**Comment by panditakshay402** [comment]
> Hey, I am new to open source. Can I contribute to this?

yes @Kundanika04

**Comment by Ishika0-0** [comment]
@panditakshay402 Can I contribute to #4 issue

**Comment by panditakshay402** [comment]
@Ishika0-0 @Kundanika04 Must Follow me and Star the Repo before sending PR

**Comment by Kundanika04** [comment]
@panditakshay402 now am I eligible?

**Comment by panditakshay402** [comment]
> @panditakshay402 now am I eligible?

Yes

**Comment by Ishika0-0** [comment]
@panditakshay402 Done! Can I contribute now

**Comment by panditakshay402** [comment]
> @panditakshay402 Done! Can I contribute now

@Ishika0-0 yes, Must follow me and star the repo before PR

**Comment by Ishika0-0** [comment]
Done!

**Comment by Ishika0-0** [comment]
@panditakshay402 I have pulled the request can you merge it

**Comment by panditakshay402** [comment]
> @panditakshay402 I have pulled the request can you merge it

Done

**Comment by Ishika0-0** [comment]
@panditakshay402 Thankyou 😊

**Comment by aryan-rohit** [comment]
@panditakshay402  assign this to me

**Comment by vivek5200** [comment]
Hey @panditakshay402  ,Please assign this task to me. I will surely follow and star your repo.

**Comment by Anjali-Git-Hub** [comment]
hi @panditakshay402 , please assign this issue to me .

**Comment by anushka9555** [comment]
Please assign this task to me.

**Comment by Kirti-Pant** [comment]
hi @panditakshay402 please assign this task to me.

**Comment by Kirti-Pant** [comment]
@panditakshay402  please merge my PR #234
