### ISSUE TITLE
PROBLEMS ON COMPETITIVE PROGRAMMING (SHORTCUTS) & (MOST OPTIMIZED) CODE ONLY

### ISSUE THREAD

**Issue by panditakshay402** [panditakshay402/Hacktoberfest2023#40]
MUST DO FOLLOW AND STAR THE REPO BEFORE PR !!! 

YOUR CODE MUST CONTAIN EXPLANATIONS
ANY LANGUAGE CAN BE USED !

**Comment by the-shivam-gupta** [comment]
assign it to me

**Comment by Somil-Shukla** [comment]
please assign this issue to me

**Comment by 1Alisha** [comment]
pls assign this task to me

**Comment by Rex1713** [comment]
can you assign this task to me
