### ISSUE TITLE
EQUILATERAL ALGORITHM IN C++

### ISSUE THREAD

**Issue by panditakshay402** [panditakshay402/Hacktoberfest2023#5]
CODE MUST CONTAIN EXPLANATION !!!

**Comment by alienishi** [comment]
Please assign this issue to me

**Comment by tvermaashutosh** [comment]
!assign

**Comment by panditakshay402** [comment]
@tvermaashutosh @alienishi  MUST FOLLOW ME , and STAR the REPO to ACCEPT PR!

**Comment by kunjshukla** [comment]
Hey there, can you please assign me this issue.

**Comment by Abhip2109** [comment]
hey @panditakshay402 please assign me this issue

**Comment by panditakshay402** [comment]
@kunjshukla @Abhip2109  MUST DO FOLLOW ME N STAR THE REPO TO GET PR!

**Comment by rahulmangla28** [comment]
Please assign this issue to me.

**Comment by AdityaDhavale** [comment]
@panditakshay402 I would like to work on this issue , will u please assign me?

**Comment by ReaganBlade** [comment]
@panditakshay402 I would like to work on this problem, it'll be great if you assign it to me.
