### ISSUE TITLE
PROBLEM ON LINKEDLIST

### ISSUE THREAD

**Issue by panditakshay402** [panditakshay402/Hacktoberfest2023#54]
DO FOLLOW ME AND STAR THE REPO BEFORE PR!!!

**Comment by krishnapatidar458** [comment]
assign ??
@panditakshay402

**Comment by DebarjunChakraborty** [comment]
@panditakshay402  Please assign this task to me. I will surely follow and star your repo.

**Comment by vagxrth** [comment]
Hey, @panditakshay402 I would love to work on the issue can you assign it to me

**Comment by AviGawande** [comment]
want to work for this issue could you please assign it to me

**Comment by SankalpHaritash21** [comment]
Hi, @panditakshay402 I would love to work on the issue can you assign it to me

**Comment by vivek5200** [comment]
Hey @panditakshay402 , Please assign this task to me. I will surely follow and star your repo.

**Comment by spardha-codinggirl** [comment]
Hi @panditakshay402 , I want to add the solution of detection of cycle or loop in the linked list using Floyd's cycle finding algorithm. Please assign this issue to me.

**Comment by vivek5200** [comment]
Please Can you Merge #92

**Comment by panditakshay402** [comment]
> Hey @panditakshay402 ,Please Can you Merge #92

@vivek5200 Read the Readme.md before PR to get accepted

**Comment by vivek5200** [comment]
hey @panditakshay402 , I followed All steps From Read.md and I put new PR #102 Please can you Review it and Merge it.

**Comment by 0nikhilkumar** [comment]
> hey @panditakshay402 , I followed All steps From Read.md and I put new PR #102 Please can you Review it and Merge it.

Bro its excluded repo it doesn't counted for hactoberfest'23

**Comment by 1Alisha** [comment]
@panditakshay402 pls assign this issue to me..

**Comment by tanjul17** [comment]
@panditakshay402 pls assign this issue to me.....

**Comment by alaykabir** [comment]
Can you please assign this to me. I am willing to work. waiting for your response.

**Comment by ReaganBlade** [comment]
I would like to work on this problem, can you please assign this to me.
