### ISSUE TITLE
PROBLEMS ON BINARY SEARCH

### ISSUE THREAD

**Issue by panditakshay402** [panditakshay402/Hacktoberfest2023#55]
DO FOLLOW ME AND STAR THE REPO BEFORE PR!!!

**Comment by DebarjunChakraborty** [comment]
@panditakshay402 Please assign this task to me. I will surely follow and star your repo.

**Comment by AviGawande** [comment]
@panditakshay402  would be glad to contribute and i hope that will assign it to me.

**Comment by deepak039543** [comment]
hey @panditakshay402 brother please assign this issue to me

**Comment by anushka9555** [comment]
Please assign this issue to me.

**Comment by Kirti-Pant** [comment]
@panditakshay402  sir, please assign this issue to me.

**Comment by Aashi19234** [comment]
@panditakshay402  please assign this issue to me.

**Comment by Aashi19234** [comment]
I have issued a pr please review it

**Comment by ashvaneetk** [comment]
@panditakshay402 Assign thus issue to me

**Comment by Rex1713** [comment]
@panditakshay402 can you assign this issue to me

**Comment by Kirti-Pant** [comment]
Sir, I've issued a PR please review it.

**Comment by Kirti-Pant** [comment]
Sir,  if you got my PR please let me know.

**Comment by Cooldude4973** [comment]
@panditakshay402 would be glad to contribute and i hope that will assign it to me.  I would be making a contribution with this question LeetCode 875 . Koko Eating Bananas

**Comment by vamus092** [comment]
assign me the issue

**Comment by mdsahilnoob** [comment]
@panditakshay402 can you assign this issue to me?

**Comment by ReaganBlade** [comment]
@panditakshay402 I Would like to work on this problem, can you please assign this to me?
