### ISSUE TITLE
PROBLEMS ON DOUBLY-LINKED LIST

### ISSUE THREAD

**Issue by panditakshay402** [panditakshay402/Hacktoberfest2023#56]
DO FOLLOW ME AND STAR THE REPO BEFORE PR!!!

**Comment by DebarjunChakraborty** [comment]
@panditakshay402 Please assign this task to me. I will surely follow and star your repo.

**Comment by deepak039543** [comment]
hey @panditakshay402 brother, Please assign this issue to me.

**Comment by vivek5200** [comment]
Hey @panditakshay402 Brother Please Assign This Issue To me .

**Comment by Wafmulla** [comment]
can you please assign this issue to me under Hacktoberfest label?

**Comment by urveesh28** [comment]
Please assign me this task . Would love to contribute

**Comment by Kirti-Pant** [comment]
@panditakshay402  sir, can you please assign this task to me ?

**Comment by ShreyaShukla03** [comment]
please check and merge PR#150

**Comment by hpk129** [comment]
please assign this task to me

**Comment by rakeem996** [comment]
@panditakshay402 Please assign this task to me. I will surely follow and star your repo.

**Comment by wasiuddinmansoori1** [comment]
Assign it to me please
