### ISSUE TITLE
GCD or HCF in C++

### ISSUE THREAD

**Issue by panditakshay402** [panditakshay402/Hacktoberfest2023#6]
CODE must contain EXPLANATION !!!

**Comment by Paras0750** [comment]
assign me this issue

**Comment by alienishi** [comment]
Please assign this issue to me 
I'll make sure to add explanation

**Comment by tvermaashutosh** [comment]
!assign

**Comment by riddhi-283** [comment]
Hello @panditakshay402 please assign me this issue!

**Comment by panditakshay402** [comment]
MUST DO FOLLOW AND STAR THE REPO @Paras0750 @tvermaashutosh @riddhi-283 @alienishi

**Comment by RashiJyotishi** [comment]
@panditakshay402  please assign this issue to me.

**Comment by AdityaDhavale** [comment]
@panditakshay402 I would love to work on this issue , please assign me

**Comment by RashiJyotishi** [comment]
please merge my pull request.

**Comment by panditakshay402** [comment]
> please merge my pull request.

@AdityaDhavale @RashiJyotishi  must follow me and star the Repo to get PR

**Comment by MaithiliSingh17** [comment]
@panditakshay402  can you please assign this to me ?

**Comment by panditakshay402** [comment]
> @panditakshay402 can you please assign this issue to me ? I am keen to solve this problem.
@MaithiliSingh17  Must Follow me and star the repo before PR

**Comment by rahulmangla28** [comment]
Please assign this to me.

**Comment by RashiJyotishi** [comment]
@panditakshay402  I have starred you and and followed you kindly give hacktoberfest accepted label in my pr.

**Comment by AdityaDhavale** [comment]
@panditakshay402 I've starred and followed you and also added HCF code in C++. Please check into it and kindly merge my PR.
